[package]
name = "oxygen"
version = "0.0.1"
edition = "2021"
authors = ["devknot devknot@protonmail.com"]
readme = "readme.md" 
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

